/**
 * Countries and States/Regions Data
 * Comprehensive list of countries and their states/regions for tax rate configuration
 * Similar to Magento's default country/region functionality
 */

export const countries = [
  { id: 'US', name: 'United States' },
  { id: 'CA', name: 'Canada' },
  { id: 'GB', name: 'United Kingdom' },
  { id: 'AU', name: 'Australia' },
  { id: 'DE', name: 'Germany' },
  { id: 'FR', name: 'France' },
  { id: 'IT', name: 'Italy' },
  { id: 'ES', name: 'Spain' },
  { id: 'NL', name: 'Netherlands' },
  { id: 'BE', name: 'Belgium' },
  { id: 'CH', name: 'Switzerland' },
  { id: 'AT', name: 'Austria' },
  { id: 'SE', name: 'Sweden' },
  { id: 'NO', name: 'Norway' },
  { id: 'DK', name: 'Denmark' },
  { id: 'FI', name: 'Finland' },
  { id: 'PL', name: 'Poland' },
  { id: 'CZ', name: 'Czech Republic' },
  { id: 'IE', name: 'Ireland' },
  { id: 'PT', name: 'Portugal' },
  { id: 'GR', name: 'Greece' },
  { id: 'MX', name: 'Mexico' },
  { id: 'BR', name: 'Brazil' },
  { id: 'AR', name: 'Argentina' },
  { id: 'CL', name: 'Chile' },
  { id: 'CO', name: 'Colombia' },
  { id: 'IN', name: 'India' },
  { id: 'CN', name: 'China' },
  { id: 'JP', name: 'Japan' },
  { id: 'KR', name: 'South Korea' },
  { id: 'SG', name: 'Singapore' },
  { id: 'MY', name: 'Malaysia' },
  { id: 'TH', name: 'Thailand' },
  { id: 'PH', name: 'Philippines' },
  { id: 'ID', name: 'Indonesia' },
  { id: 'VN', name: 'Vietnam' },
  { id: 'NZ', name: 'New Zealand' },
  { id: 'ZA', name: 'South Africa' },
  { id: 'AE', name: 'United Arab Emirates' },
  { id: 'SA', name: 'Saudi Arabia' },
  { id: 'IL', name: 'Israel' },
  { id: 'TR', name: 'Turkey' },
  { id: 'RU', name: 'Russia' }
]

export const statesByCountry = {
  US: [
    { id: '', name: 'All States/Regions' },
    { id: 'AL', name: 'Alabama' },
    { id: 'AK', name: 'Alaska' },
    { id: 'AZ', name: 'Arizona' },
    { id: 'AR', name: 'Arkansas' },
    { id: 'CA', name: 'California' },
    { id: 'CO', name: 'Colorado' },
    { id: 'CT', name: 'Connecticut' },
    { id: 'DE', name: 'Delaware' },
    { id: 'FL', name: 'Florida' },
    { id: 'GA', name: 'Georgia' },
    { id: 'HI', name: 'Hawaii' },
    { id: 'ID', name: 'Idaho' },
    { id: 'IL', name: 'Illinois' },
    { id: 'IN', name: 'Indiana' },
    { id: 'IA', name: 'Iowa' },
    { id: 'KS', name: 'Kansas' },
    { id: 'KY', name: 'Kentucky' },
    { id: 'LA', name: 'Louisiana' },
    { id: 'ME', name: 'Maine' },
    { id: 'MD', name: 'Maryland' },
    { id: 'MA', name: 'Massachusetts' },
    { id: 'MI', name: 'Michigan' },
    { id: 'MN', name: 'Minnesota' },
    { id: 'MS', name: 'Mississippi' },
    { id: 'MO', name: 'Missouri' },
    { id: 'MT', name: 'Montana' },
    { id: 'NE', name: 'Nebraska' },
    { id: 'NV', name: 'Nevada' },
    { id: 'NH', name: 'New Hampshire' },
    { id: 'NJ', name: 'New Jersey' },
    { id: 'NM', name: 'New Mexico' },
    { id: 'NY', name: 'New York' },
    { id: 'NC', name: 'North Carolina' },
    { id: 'ND', name: 'North Dakota' },
    { id: 'OH', name: 'Ohio' },
    { id: 'OK', name: 'Oklahoma' },
    { id: 'OR', name: 'Oregon' },
    { id: 'PA', name: 'Pennsylvania' },
    { id: 'RI', name: 'Rhode Island' },
    { id: 'SC', name: 'South Carolina' },
    { id: 'SD', name: 'South Dakota' },
    { id: 'TN', name: 'Tennessee' },
    { id: 'TX', name: 'Texas' },
    { id: 'UT', name: 'Utah' },
    { id: 'VT', name: 'Vermont' },
    { id: 'VA', name: 'Virginia' },
    { id: 'WA', name: 'Washington' },
    { id: 'WV', name: 'West Virginia' },
    { id: 'WI', name: 'Wisconsin' },
    { id: 'WY', name: 'Wyoming' },
    { id: 'DC', name: 'District of Columbia' }
  ],
  CA: [
    { id: '', name: 'All Provinces/Territories' },
    { id: 'AB', name: 'Alberta' },
    { id: 'BC', name: 'British Columbia' },
    { id: 'MB', name: 'Manitoba' },
    { id: 'NB', name: 'New Brunswick' },
    { id: 'NL', name: 'Newfoundland and Labrador' },
    { id: 'NS', name: 'Nova Scotia' },
    { id: 'NT', name: 'Northwest Territories' },
    { id: 'NU', name: 'Nunavut' },
    { id: 'ON', name: 'Ontario' },
    { id: 'PE', name: 'Prince Edward Island' },
    { id: 'QC', name: 'Quebec' },
    { id: 'SK', name: 'Saskatchewan' },
    { id: 'YT', name: 'Yukon' }
  ],
  GB: [
    { id: '', name: 'All Regions' },
    { id: 'ENG', name: 'England' },
    { id: 'SCT', name: 'Scotland' },
    { id: 'WLS', name: 'Wales' },
    { id: 'NIR', name: 'Northern Ireland' }
  ],
  AU: [
    { id: '', name: 'All States/Territories' },
    { id: 'ACT', name: 'Australian Capital Territory' },
    { id: 'NSW', name: 'New South Wales' },
    { id: 'NT', name: 'Northern Territory' },
    { id: 'QLD', name: 'Queensland' },
    { id: 'SA', name: 'South Australia' },
    { id: 'TAS', name: 'Tasmania' },
    { id: 'VIC', name: 'Victoria' },
    { id: 'WA', name: 'Western Australia' }
  ],
  DE: [
    { id: '', name: 'All States' },
    { id: 'BW', name: 'Baden-Württemberg' },
    { id: 'BY', name: 'Bavaria' },
    { id: 'BE', name: 'Berlin' },
    { id: 'BB', name: 'Brandenburg' },
    { id: 'HB', name: 'Bremen' },
    { id: 'HH', name: 'Hamburg' },
    { id: 'HE', name: 'Hesse' },
    { id: 'MV', name: 'Mecklenburg-Vorpommern' },
    { id: 'NI', name: 'Lower Saxony' },
    { id: 'NW', name: 'North Rhine-Westphalia' },
    { id: 'RP', name: 'Rhineland-Palatinate' },
    { id: 'SL', name: 'Saarland' },
    { id: 'SN', name: 'Saxony' },
    { id: 'ST', name: 'Saxony-Anhalt' },
    { id: 'SH', name: 'Schleswig-Holstein' },
    { id: 'TH', name: 'Thuringia' }
  ],
  FR: [
    { id: '', name: 'All Regions' },
    { id: 'ARA', name: 'Auvergne-Rhône-Alpes' },
    { id: 'BFC', name: 'Bourgogne-Franche-Comté' },
    { id: 'BRE', name: 'Brittany' },
    { id: 'CVL', name: 'Centre-Val de Loire' },
    { id: 'COR', name: 'Corsica' },
    { id: 'GES', name: 'Grand Est' },
    { id: 'HDF', name: 'Hauts-de-France' },
    { id: 'IDF', name: 'Île-de-France' },
    { id: 'NOR', name: 'Normandy' },
    { id: 'NAQ', name: 'Nouvelle-Aquitaine' },
    { id: 'OCC', name: 'Occitanie' },
    { id: 'PDL', name: 'Pays de la Loire' },
    { id: 'PAC', name: "Provence-Alpes-Côte d'Azur" }
  ],
  IT: [
    { id: '', name: 'All Regions' },
    { id: 'ABR', name: 'Abruzzo' },
    { id: 'BAS', name: 'Basilicata' },
    { id: 'CAL', name: 'Calabria' },
    { id: 'CAM', name: 'Campania' },
    { id: 'EMR', name: 'Emilia-Romagna' },
    { id: 'FVG', name: 'Friuli-Venezia Giulia' },
    { id: 'LAZ', name: 'Lazio' },
    { id: 'LIG', name: 'Liguria' },
    { id: 'LOM', name: 'Lombardy' },
    { id: 'MAR', name: 'Marche' },
    { id: 'MOL', name: 'Molise' },
    { id: 'PIE', name: 'Piedmont' },
    { id: 'PUG', name: 'Apulia' },
    { id: 'SAR', name: 'Sardinia' },
    { id: 'SIC', name: 'Sicily' },
    { id: 'TOS', name: 'Tuscany' },
    { id: 'TAA', name: 'Trentino-Alto Adige' },
    { id: 'UMB', name: 'Umbria' },
    { id: 'VDA', name: 'Aosta Valley' },
    { id: 'VEN', name: 'Veneto' }
  ],
  ES: [
    { id: '', name: 'All Regions' },
    { id: 'AN', name: 'Andalusia' },
    { id: 'AR', name: 'Aragon' },
    { id: 'AS', name: 'Asturias' },
    { id: 'IB', name: 'Balearic Islands' },
    { id: 'PV', name: 'Basque Country' },
    { id: 'CN', name: 'Canary Islands' },
    { id: 'CB', name: 'Cantabria' },
    { id: 'CL', name: 'Castile and León' },
    { id: 'CM', name: 'Castile-La Mancha' },
    { id: 'CT', name: 'Catalonia' },
    { id: 'EX', name: 'Extremadura' },
    { id: 'GA', name: 'Galicia' },
    { id: 'MD', name: 'Madrid' },
    { id: 'MC', name: 'Murcia' },
    { id: 'NC', name: 'Navarre' },
    { id: 'RI', name: 'La Rioja' },
    { id: 'VC', name: 'Valencian Community' }
  ],
  MX: [
    { id: '', name: 'All States' },
    { id: 'AGU', name: 'Aguascalientes' },
    { id: 'BCN', name: 'Baja California' },
    { id: 'BCS', name: 'Baja California Sur' },
    { id: 'CAM', name: 'Campeche' },
    { id: 'CHP', name: 'Chiapas' },
    { id: 'CHH', name: 'Chihuahua' },
    { id: 'COA', name: 'Coahuila' },
    { id: 'COL', name: 'Colima' },
    { id: 'DIF', name: 'Mexico City' },
    { id: 'DUR', name: 'Durango' },
    { id: 'GUA', name: 'Guanajuato' },
    { id: 'GRO', name: 'Guerrero' },
    { id: 'HID', name: 'Hidalgo' },
    { id: 'JAL', name: 'Jalisco' },
    { id: 'MEX', name: 'Mexico' },
    { id: 'MIC', name: 'Michoacán' },
    { id: 'MOR', name: 'Morelos' },
    { id: 'NAY', name: 'Nayarit' },
    { id: 'NLE', name: 'Nuevo León' },
    { id: 'OAX', name: 'Oaxaca' },
    { id: 'PUE', name: 'Puebla' },
    { id: 'QUE', name: 'Querétaro' },
    { id: 'ROO', name: 'Quintana Roo' },
    { id: 'SLP', name: 'San Luis Potosí' },
    { id: 'SIN', name: 'Sinaloa' },
    { id: 'SON', name: 'Sonora' },
    { id: 'TAB', name: 'Tabasco' },
    { id: 'TAM', name: 'Tamaulipas' },
    { id: 'TLA', name: 'Tlaxcala' },
    { id: 'VER', name: 'Veracruz' },
    { id: 'YUC', name: 'Yucatán' },
    { id: 'ZAC', name: 'Zacatecas' }
  ],
  BR: [
    { id: '', name: 'All States' },
    { id: 'AC', name: 'Acre' },
    { id: 'AL', name: 'Alagoas' },
    { id: 'AP', name: 'Amapá' },
    { id: 'AM', name: 'Amazonas' },
    { id: 'BA', name: 'Bahia' },
    { id: 'CE', name: 'Ceará' },
    { id: 'DF', name: 'Distrito Federal' },
    { id: 'ES', name: 'Espírito Santo' },
    { id: 'GO', name: 'Goiás' },
    { id: 'MA', name: 'Maranhão' },
    { id: 'MT', name: 'Mato Grosso' },
    { id: 'MS', name: 'Mato Grosso do Sul' },
    { id: 'MG', name: 'Minas Gerais' },
    { id: 'PA', name: 'Pará' },
    { id: 'PB', name: 'Paraíba' },
    { id: 'PR', name: 'Paraná' },
    { id: 'PE', name: 'Pernambuco' },
    { id: 'PI', name: 'Piauí' },
    { id: 'RJ', name: 'Rio de Janeiro' },
    { id: 'RN', name: 'Rio Grande do Norte' },
    { id: 'RS', name: 'Rio Grande do Sul' },
    { id: 'RO', name: 'Rondônia' },
    { id: 'RR', name: 'Roraima' },
    { id: 'SC', name: 'Santa Catarina' },
    { id: 'SP', name: 'São Paulo' },
    { id: 'SE', name: 'Sergipe' },
    { id: 'TO', name: 'Tocantins' }
  ],
  IN: [
    { id: '', name: 'All States/UTs' },
    { id: 'AN', name: 'Andaman and Nicobar Islands' },
    { id: 'AP', name: 'Andhra Pradesh' },
    { id: 'AR', name: 'Arunachal Pradesh' },
    { id: 'AS', name: 'Assam' },
    { id: 'BR', name: 'Bihar' },
    { id: 'CH', name: 'Chandigarh' },
    { id: 'CT', name: 'Chhattisgarh' },
    { id: 'DN', name: 'Dadra and Nagar Haveli' },
    { id: 'DD', name: 'Daman and Diu' },
    { id: 'DL', name: 'Delhi' },
    { id: 'GA', name: 'Goa' },
    { id: 'GJ', name: 'Gujarat' },
    { id: 'HR', name: 'Haryana' },
    { id: 'HP', name: 'Himachal Pradesh' },
    { id: 'JK', name: 'Jammu and Kashmir' },
    { id: 'JH', name: 'Jharkhand' },
    { id: 'KA', name: 'Karnataka' },
    { id: 'KL', name: 'Kerala' },
    { id: 'LD', name: 'Lakshadweep' },
    { id: 'MP', name: 'Madhya Pradesh' },
    { id: 'MH', name: 'Maharashtra' },
    { id: 'MN', name: 'Manipur' },
    { id: 'ML', name: 'Meghalaya' },
    { id: 'MZ', name: 'Mizoram' },
    { id: 'NL', name: 'Nagaland' },
    { id: 'OR', name: 'Odisha' },
    { id: 'PY', name: 'Puducherry' },
    { id: 'PB', name: 'Punjab' },
    { id: 'RJ', name: 'Rajasthan' },
    { id: 'SK', name: 'Sikkim' },
    { id: 'TN', name: 'Tamil Nadu' },
    { id: 'TG', name: 'Telangana' },
    { id: 'TR', name: 'Tripura' },
    { id: 'UP', name: 'Uttar Pradesh' },
    { id: 'UT', name: 'Uttarakhand' },
    { id: 'WB', name: 'West Bengal' }
  ]
}

// Helper function to get states for a country
export const getStatesForCountry = (countryId) => {
  if (!countryId) return []
  return statesByCountry[countryId] || [{ id: '', name: 'All States/Regions' }]
}

// Helper function to get country name by ID
export const getCountryName = (countryId) => {
  const country = countries.find(c => c.id === countryId)
  return country ? country.name : countryId
}

// Helper function to get state name by ID and country
export const getStateName = (stateId, countryId) => {
  if (!stateId) return 'All States/Regions'
  const states = getStatesForCountry(countryId)
  const state = states.find(s => s.id === stateId)
  return state ? state.name : stateId
}

